### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by xuko** [aimok04/grocy-for-wear-os#1]
I configure my credentials data in companion app but In wear os app I get "Could not connect to server".
![screenshot-2024-07-21-13-37-13](https://github.com/user-attachments/assets/c4674180-92c7-4e3c-ba48-ebcb1ac6db61)

**Comment by aimok04** [comment]
Hi, I could not reproduce this error. Please make sure that:

1. Your instance is accessible from the internet
2. The credentials are valid (You could use the Grocy Android app  f.e. to verify your API key)
3. Your Grocy instance is running a compatible version
